# Generated by Django 5.0.7 on 2024-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('literacy', 'Literacy'), ('travel', 'Travel'), ('food', 'Food'), ('personal', 'Personal'), ('relations', 'Family/Relations'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('artistic', 'Artistic'), ('general', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
