# Generated by Django 5.0.6 on 2024-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blog_category_alter_blog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('literacy', 'Literacy'), ('travel', 'Travel'), ('food', 'Food'), ('personal', 'Personal'), ('relations', 'Family/Relations'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('artistic', 'Artistic'), ('general', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
