# Generated by Django 5.0.6 on 2024-07-22 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_category_alter_blog_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('literacy', 'Literacy'), ('travel', 'Travel'), ('food', 'Food'), ('personal', 'Personal'), ('relations', 'Family/Relations'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('artistic', 'Artistic'), ('general', 'Other')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
