# Generated by Django 5.0.6 on 2024-07-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blog_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('literacy', 'Literacy'), ('travel', 'Travel'), ('food', 'Food'), ('personal', 'Personal'), ('relations', 'Family/Relations'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('artistic', 'Artistic'), ('general', 'Other')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
