# Generated by Django 5.0.7 on 2024-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='publish', max_length=10),
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
