# Generated by Django 5.0.7 on 2024-07-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_blog_status_delete_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish')], default='publish', max_length=10),
        ),
    ]
