# Generated by Django 5.0.7 on 2024-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('literacy', 'Literacy'), ('travel', 'Travel'), ('food', 'Food'), ('personal', 'Personal'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health'), ('fashion', 'Fashion'), ('sports', 'Sports'), ('artistic', 'Artistic'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
